import {createLocalId,putQueueItem,listQueueItems,putEvidence,listEvidence} from "./local-first.js";
import {showNotice} from "./ui.js";
let cteContext=null;
let cteState={tickets:[]};
let selectedEvidence=[];
let selectedTicket=null;
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function nowLocal(){const d=new Date(),pad=n=>String(n).padStart(2,"0");return {fecha:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,hora:`${pad(d.getHours())}:${pad(d.getMinutes())}`}}
function initials(name=""){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"N"}
function normalizeImage(v){if(!v)return "";if(typeof v==="object")return normalizeImage(v.url||v.src||v.imageUrl||v.fileUrl||v.photo?.url||v.image?.url);const s=String(v).trim();if(s.startsWith("wix:image://v1/")){const id=s.slice(15).split("/")[0];return id?`https://static.wixstatic.com/media/${id}`:""}return s}
function userName(){return String(cteContext?.user?.nombreVisible||cteContext?.user?.nombre||"Usuario")}
function userAvatar(){return normalizeImage(cteContext?.user?.avatar||cteContext?.user?.avatarUrl||cteContext?.user?.foto||cteContext?.user?.photo||cteContext?.user?.profile?.photo)}
function paintIdentity(){const name=userName(),avatar=$("#cteAvatar"),url=userAvatar();$("#cteUserName").textContent=name;avatar.textContent=url?"":initials(name);avatar.style.backgroundImage=url?`url("${url.replace(/"/g,"%22")}")`:"";avatar.style.backgroundSize="cover";avatar.style.backgroundPosition="center";const n=nowLocal();$("#cteMeta").textContent=`Folio: — · ${n.fecha} · ${n.hora}`}
function setTab(name){$("#btnCteNueva").classList.toggle("is-active",name==="nueva");$("#btnCteTickets").classList.toggle("is-active",name==="tickets");$("#cteNuevaView").hidden=name!=="nueva";$("#cteTicketsView").hidden=name!=="tickets";$("#cteTicketDetailView").hidden=true;if(name==="tickets")renderTickets()}
function clearForm(){$("#cteClasificacion").value="";$("#cteServicio").value="";$("#cteDescripcion").value="";$("#cteEvidencias").value="";selectedEvidence=[];renderEvidence();$("#cteResult").hidden=true;$("#btnCteGuardar").hidden=false;$("#btnCteNuevo").hidden=true;paintIdentity()}
function renderEvidence(){const box=$("#cteEvidenceSelected");box.innerHTML=selectedEvidence.map((x,i)=>`<div class="cte-evidence-chip"><span>${esc(x.name)}</span><button type="button" data-remove-evidence="${i}" aria-label="Eliminar">×</button></div>`).join("");box.hidden=!selectedEvidence.length}
function ticketState(e){return String(e?.seguimientoEstado||e?.estatus||"SIN_ASIGNAR").toUpperCase()}
function stateLabel(e){const s=ticketState(e);return s==="ATENDIDO"?"Atendido":s==="EN_SEGUIMIENTO"?"En atención":"Recibido"}
function ticketFolio(e){const f=String(e?.folio||e?.codigo||"").trim(),m=f.match(/(\d+)$/);return m?m[1].padStart(4,"0").slice(-4):(f||"—")}
function ticketDate(e){const raw=e?.fechaHoraEvento||e?.fechaEvento||e?.fecha||e?.fechaHoraRegistro||"";if(!raw)return "—";const d=new Date(raw);return Number.isNaN(d.getTime())?String(raw):d.toLocaleDateString("es-MX")}
function classification(e){const x=String(e?.clasificacionCte||"").toUpperCase();return ({QUEJA:"Queja",INFORMACION:"Información",SUGERENCIA:"Sugerencia",SOLICITUD:"Solicitud"})[x]||"Atención"}
function renderTickets(){const items=Array.isArray(cteState.tickets)?cteState.tickets:[];$("#cteTicketsCount").textContent=`${items.length} ticket${items.length===1?"":"s"}`;$("#cteTicketsList").innerHTML=items.length?items.map(e=>{const id=String(e.id||e._id||""),s=ticketState(e),cl=s==="ATENDIDO"?"is-attended":s==="EN_SEGUIMIENTO"?"is-progress":"is-open";return `<button class="cte-ticket" type="button" data-cte-id="${esc(id)}"><span class="cte-folio">${esc(ticketFolio(e))}</span><span class="cte-ticket-date">${esc(ticketDate(e))}</span><span class="cte-ticket-copy"><strong>${esc(classification(e))}</strong><span>${esc(e?.lugar||e?.descripcion||"")}</span></span><span class="cte-status ${cl}">${esc(stateLabel(e))}</span></button>`}).join(""):'<div class="cte-empty">No tienes tickets de atención registrados.</div>'}
function openTicket(id){selectedTicket=(cteState.tickets||[]).find(x=>String(x.id||x._id||"")===String(id))||null;if(!selectedTicket)return;$("#cteTicketsView").hidden=true;$("#cteTicketDetailView").hidden=false;const e=selectedTicket,seg=Array.isArray(e?.seguimientos)?e.seguimientos:[];$("#cteTicketDetail").innerHTML=`<div class="cte-detail-line"><span>Ticket</span><strong>${esc(ticketFolio(e))}</strong></div><div class="cte-detail-line"><span>Estatus</span><strong>${esc(stateLabel(e))}</strong></div><div class="cte-detail-line"><span>Clasificación</span><strong>${esc(classification(e))}</strong></div><div class="cte-detail-line"><span>Servicio</span><strong>${esc(e?.lugar||"—")}</strong></div><div class="cte-detail-block"><span>Descripción</span><p>${esc(e?.descripcion||"—")}</p></div>${seg.length?`<div class="cte-detail-block"><span>Seguimiento</span>${seg.map(s=>`<p><strong>${esc(s.autorNombre||"Atención")}</strong> · ${esc(s.nota||"")}</p>`).join("")}</div>`:""}`}
async function saveTicket(){const n=nowLocal(),detail={fecha:n.fecha,hora:n.hora,lugar:String($("#cteServicio").value||"").trim(),descripcion:String($("#cteDescripcion").value||"").trim(),clasificacionCte:String($("#cteClasificacion").value||"").trim(),fuente:"CTE",requiereSeguimiento:true,esTip:false,comentarios:"",programacionId:""};if(!detail.clasificacionCte||!detail.lugar||!detail.descripcion){showNotice("Completa Clasificación, Servicio y Descripción.");return}const localId=createLocalId("cte"),createdLocalAt=new Date().toISOString();await putQueueItem({localId,module:"CTE",operation:"REGISTER_CTE_EVENT",payload:detail,syncStatus:"PENDIENTE",createdLocalAt,lastSyncAttempt:null,syncError:"",syncAttempts:0,serverId:"",serverFolio:""});for(const file of selectedEvidence){if(file.size>10*1024*1024){showNotice(`La evidencia "${file.name}" excede 10 MB y no fue guardada.`);continue}await putEvidence({evidenceId:createLocalId("evi"),localId,file,name:file.name,type:file.type||"application/octet-stream",size:file.size,syncStatus:"PENDIENTE",syncAttempts:0,lastSyncAttempt:null,syncError:""})}$("#cteResult").textContent=navigator.onLine?"Ticket guardado. Sincronizando...":"Ticket guardado en el dispositivo. Se sincronizará al recuperar conexión.";$("#cteResult").hidden=false;$("#btnCteGuardar").hidden=true;$("#btnCteNuevo").hidden=false;document.dispatchEvent(new CustomEvent("nexus:cte-local-saved",{detail:{localId}}))}
export function setCteContext(context){cteContext=context||null}
export function getCteSnapshot(){return cteState}
export function openCteTickets(){if(cteContext?.authenticated!==true)return;setTab("tickets");$("#cteModal").hidden=false}
export function setCteState(next={}){cteState={tickets:Array.isArray(next.tickets)?next.tickets:[]};renderTickets()}
export function openCteTicket(id){if(cteContext?.authenticated!==true)return false;const ok=(cteState.tickets||[]).some(x=>String(x.id||x._id||"")===String(id));setTab("tickets");$("#cteModal").hidden=false;if(ok)openTicket(id);return ok}
export function openCte(){if(cteContext?.authenticated!==true)return;clearForm();setTab("nueva");$("#cteModal").hidden=false}
export async function getPendingCteEvents(){return (await listQueueItems("CTE")).filter(x=>x.syncStatus!=="SINCRONIZADO")}
export async function getCteEvidence(localId){return listEvidence(localId)}
export async function updateCteQueue(item){await putQueueItem(item)}
export async function updateCteEvidence(item){await putEvidence(item)}
export async function notifyCteSynced(){renderTickets()}
export function initCte(){const modal=$("#cteModal");if(!modal)return;$("#btnCloseCte").addEventListener("click",()=>modal.hidden=true);modal.addEventListener("click",e=>{if(e.target===modal)modal.hidden=true});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!modal.hidden)modal.hidden=true});$("#btnCteNueva").addEventListener("click",()=>{clearForm();setTab("nueva")});$("#btnCteTickets").addEventListener("click",()=>setTab("tickets"));$("#btnCteTicketBack").addEventListener("click",()=>setTab("tickets"));$("#cteTicketsList").addEventListener("click",e=>{const row=e.target.closest("[data-cte-id]");if(row)openTicket(row.dataset.cteId)});$("#cteEvidencias").addEventListener("change",e=>{selectedEvidence=[...selectedEvidence,...Array.from(e.target.files||[])].slice(0,10);e.target.value="";renderEvidence()});$("#cteEvidenceSelected").addEventListener("click",e=>{const b=e.target.closest("[data-remove-evidence]");if(!b)return;selectedEvidence.splice(Number(b.dataset.removeEvidence),1);renderEvidence()});$("#btnCteGuardar").addEventListener("click",()=>saveTicket().catch(error=>showNotice(error?.message||"No fue posible guardar el ticket.")));$("#btnCteNuevo").addEventListener("click",clearForm);window.addEventListener("online",()=>document.dispatchEvent(new CustomEvent("nexus:cte-sync-request")))}
