const TVDI_HLS="https://motortv.scad.mx/hls/canal.m3u8";
let context=null,hls=null,tvMuted=true,communityPollTimer=null,communityVideoKey="";
const $=s=>document.querySelector(s);

function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function destroyHls(){if(hls){hls.destroy();hls=null}const v=$("#tvVideo");if(!v)return;v.pause();v.removeAttribute("src");v.load()}
function stopCommunityPolling(){if(communityPollTimer){clearInterval(communityPollTimer);communityPollTimer=null}}
function setPlaceholder(active){const v=$("#tvVideo"),p=$("#tvPlaceholder"),c=$("#tvScreenCenter");if(p)p.hidden=!active;if(c)c.hidden=!active;if(v)v.hidden=active}
function playUrl(url){stopCommunityPolling();communityVideoKey="";const c=$("#tvScreenCenter");if(c)c.innerHTML='<span class="tv-play">▶</span>';destroyHls();const v=$("#tvVideo");if(!v||!url){setPlaceholder(true);return}setPlaceholder(false);v.muted=tvMuted;if(/\.m3u8($|\?)/i.test(url)){if(v.canPlayType("application/vnd.apple.mpegurl")){v.src=url;v.play().catch(()=>{});return}if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:false,backBufferLength:30});hls.loadSource(url);hls.attachMedia(v);hls.on(Hls.Events.MANIFEST_PARSED,()=>v.play().catch(()=>{}));hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)setPlaceholder(true)});return}}v.src=url;v.play().catch(()=>{})}
function youtubeEmbedUrl(tv){const id=String(tv?.youtubeId||"").trim();if(!id)return"";const start=Math.max(0,Math.floor(Number(tv?.segundoInicio)||0));const u=new URL(`https://www.youtube.com/embed/${encodeURIComponent(id)}`);u.searchParams.set("autoplay","1");u.searchParams.set("mute",tvMuted?"1":"0");u.searchParams.set("playsinline","1");u.searchParams.set("controls","1");u.searchParams.set("rel","0");u.searchParams.set("enablejsapi","1");u.searchParams.set("start",String(start));u.searchParams.set("origin",location.origin);return u.toString()}
function sendYoutubeCommand(func){const f=$("#tvCommunityFrame");if(f?.contentWindow)f.contentWindow.postMessage(JSON.stringify({event:"command",func,args:[]}),"https://www.youtube.com")}
function renderEoTransmission(force=false){const tv=context?.tv,id=String(tv?.youtubeId||"").trim(),center=$("#tvScreenCenter");if(!id){communityVideoKey="";destroyHls();setPlaceholder(true);if(center)center.innerHTML='<span class="tv-play">▶</span>';return}const key=`${tv?.modo||""}:${id}`;if(!force&&communityVideoKey===key)return;communityVideoKey=key;destroyHls();const v=$("#tvVideo"),p=$("#tvPlaceholder");if(v)v.hidden=true;if(p)p.hidden=false;if(center){center.hidden=false;center.innerHTML=`<iframe id="tvCommunityFrame" class="tv-youtube-frame" src="${esc(youtubeEmbedUrl(tv))}" title="${esc(tv.titulo||"TV SCaD")}" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe>`}}
async function refreshEoTransmission(){if($("#tvMonitor")?.dataset.channel!=="eo"||!context?.memberId)return;try{const u=new URL("https://www.scad.mx/_functions/nexusPwaContext");u.searchParams.set("memberId",context.memberId);u.searchParams.set("t",Date.now());const r=await fetch(u,{cache:"no-store",credentials:"omit"}),fresh=await r.json();if(!r.ok||!fresh?.ok)return;const previous=`${context?.tv?.modo||""}:${context?.tv?.youtubeId||""}`,next=`${fresh?.tv?.modo||""}:${fresh?.tv?.youtubeId||""}`;context.tv=fresh.tv||null;if(previous!==next)renderEoTransmission(true)}catch(e){console.error("NEXUS | TV SCaD | REFRESH_ERROR",e)}}
function playEo(){renderEoTransmission(true);stopCommunityPolling();communityPollTimer=setInterval(refreshEoTransmission,10000)}
function setChannel(ch){const m=$("#tvMonitor");if(m)m.dataset.channel=ch;document.querySelectorAll(".channel[data-channel]").forEach(b=>b.classList.toggle("is-active",b.dataset.channel===ch));if(ch==="eo")playEo();else playUrl(TVDI_HLS)}
export function setTvContext(next){context=next||null;if($("#tvMonitor")?.dataset.channel==="eo")playEo()}
export function initTv(){const m=$("#tvMonitor"),x=$("#btnTvExpand"),c=$(".tv-controls");if(!m||!c)return;m.dataset.channel="internet";c.addEventListener("click",e=>{const b=e.target.closest("[data-channel]");if(b)setChannel(b.dataset.channel)});x?.addEventListener("click",async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(m.requestFullscreen)await m.requestFullscreen()}catch{}});$("#btnTvMute")?.addEventListener("click",()=>{tvMuted=!tvMuted;const v=$("#tvVideo"),i=$("#tvMuteIcon");if(v)v.muted=tvMuted;if(i)i.textContent=tvMuted?"🔇":"🔊";if(m.dataset.channel==="eo")sendYoutubeCommand(tvMuted?"mute":"unMute");else if(!tvMuted)v?.play().catch(()=>{})});setChannel("internet")}
